model:
  name: "UNet"
  n_channels: 6
  n_classes: 1
  n_filters: 8
  kernel_size: 3
  scale:
    - 1
    - 2
  bilinear: True
add_normals: True
sensor:
    name: "HDL64"
    proj_type: "conv" # projective
    nb_layers: 64
    fov_up: 85.0
    fov_down: 115.0
    res_yaw: 2048
    res_pitch: 64
    img_prop:
      width: 2048
      height: 64
    img_means: #range,z,signal
      - 12.12
      - -1.04
      - 0.21
    img_stds: #range,z,signal
      - 12.32
      - 0.86
      - 0.16