name: "unet_gt"
projection:
  proj_type: 'layers'
  res_yaw: 2048
  nb_layers: 64
img_means: #range,z,signal
  - 12.12
  - -1.04
  - 0.21
img_stds: #range,z,signal
  - 12.32
  - 0.86
  - 0.16
add_normals: False
model:
  n_channels: 3
  n_classes: 1
  n_filters: 8
  scale:
    - 1
    - 2
weights: '/home/leonardo/Dev/github/smutsia/ckpt/ground_detection/unet_best.pth'
gpu: 0